const town_name = ["Eanverness",
    "Rachdale",
    "Waeldestone",
    "Banrockburn",
    "Hewe",
    "Gillamoor",
    "Harthwaite",
    "Pinnella Pass",
    "Wavemeet",
    "Stawford",
    "Nantgarth" ,
    "Gormsey" ,
    "Briar Glen" ,
    "Transmere" ,
    "Hornsey" ,
    "Peatsland" ,
    "Bradfordshire" ,
    "Dewhurst" ,
    "Inverness" ,
    "Holbeck"];